package kr.co.noerror.DTO;

import org.springframework.stereotype.Repository;

import lombok.Data;

@Data
@Repository("inbound_DTO")
public class inbound_DTO {
	
	int IIDX, ITEM_QTY;
	String INBOUND_CODE, PCH_CODE, ITEM_CODE, ITEM_DEL, ITEM_EXP, WH_CODE;
	String IN_STATUS, INBOUND_DATE, EMPLOYEE_CODE, INB_MEMO, INB_INSERT_DATE, INB_MODIFY_DATE, IND_IN_STATUS;
	
	//join view테이블 컬럼 
	int PIDX, ITM_IDX, P_QTY, ITEM_COST;
	Long PAY_AMOUNT;
	String ITEM_NAME, ITEM_SPEC, ITEM_UNIT, ITEM_CLASS1, ITEM_CLASS2, ITM_FILE_RENM;
	String DUE_DATE, PCH_STATUS,REQUEST_DATE, PAY_METHOD, PCH_MEMO;
	String COMPANY_CODE, COMPANY_NAME, CEO_NAME, BIZ_NUM, COM_ZIP, COM_ADDR1, COM_ADDR2, COM_FILE_RENM;
	String MANAGER_NAME, MANAGER_CODE, MNG_EMAIL, MNG_TEL, MNG_PHONE, MNG_FAX, MNG_POSITION, MNG_PART, COM_MEMO;
	String WH_NAME, IND_PCH_CD;
	
	Long sum;

}
