package kr.co.noerror.DTO;

import org.springframework.stereotype.Repository;

import lombok.Data;

@Data
@Repository("outbound_DTO")
public class outbound_DTO {
	
	int OIDX;
	String OUTBOUND_CODE, ORD_CODE, OUT_STATUS;
	String OUTBOUND_DATE, EMPLOYEE_CODE, OUT_MEMO, OUT_INSERT_DATE, OUT_MODIFY_DATE;
	
	//조인용 변수
	int OUT_PRODUCT_QTY, ORD_QTY, PAY_AMOUNT;
	String PRODUCT_CODE, INSERT_DATE;
	String DUE_DATE, ORDER_STATUS, REQUEST_DATE, PAY_METHOD, WH_NAME;
	String COMPANY_CODE, COMPANY_NAME, BIZ_NUM, CEO_NAME, MANAGER_NAME, MNG_TEL, COM_ZIP, COM_ADDR1, COM_ADDR2;
	String ENAME, PRODUCT_NAME, PRODUCT_SPEC, PRODUCT_UNIT, PRODUCT_COST, PRODUCT_CLASS1, PRODUCT_CLASS2;
	
	
	
	
	

}
