package kr.co.noerror.DTO;

import org.springframework.stereotype.Repository;

import lombok.Data;

@Data
@Repository("plan_DTO")
public class plan_DTO {
	
	private Long pidx;                     // NUMBER GENERATED BY DEFAULT AS IDENTITY
    private String plan_code;               // VARCHAR2(10 CHAR) NOT NULL
    private String bom_code;                // VARCHAR2(10 CHAR) NOT NULL
    private String order_code;              // VARCHAR2(10 CHAR), NULL 가능
    private String product_code;            // VARCHAR2(10 CHAR) NOT NULL
    private String product_name;            
    private Integer product_qty;            // NUMBER NOT NULL
    private String product_spec;
    private String product_unit;            
    private String priority;               // VARCHAR2(10 CHAR) NOT NULL ('긴급', '높음', '보통')
    private String start_date;                // DATE NOT NULL
    private String due_date;                  // DATE NOT NULL
    private String company_code;            // VARCHAR2(10 CHAR) NOT NULL
    private String company_name;            
    private String emp_code;                // VARCHAR2(10 CHAR) NOT NULL
    private String emp_name;                
    private String plan_status;          // VARCHAR2(10 CHAR) NOT NULL ('계획', '생산중', '생산완료')
    private String mrp_status;               // VARCHAR2(10 CHAR) NOT NULL ('미완료', '완료')
    private String memo;                   // CLOB
    private String plan_date;            
    private String modify_date;          

}
