package kr.co.noerror.DTO;

import org.springframework.stereotype.Repository;

import lombok.Data;

@Data
@Repository("products_DTO")
public class products_DTO {
	
	//완제품 테이블(PRODUCTS) 컬럼
	int PIDX;
	String PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, PRODUCT_CLASS1, PRODUCT_CLASS2;
	String PRODUCT_SPEC, PRODUCT_UNIT, PRODUCT_COST, PRODUCT_PRICE, PD_SAFE_STOCK;
	
	String PD_FILE_NM, PD_FILE_RENM, PD_API_FNM, PD_IMG_SRC;
	String PD_USE_FLAG, PD_EXP_FLAG, PD_MEMO, PD_INSERT_DATE, PD_MODIFY_DATE;
	
	
	//부자재테이블(ITEMS) 컬럼 
	int IIDX;
	String ITEM_CODE, ITEM_NAME, ITEM_TYPE, ITEM_CLASS1, ITEM_CLASS2;
	String ITEM_SPEC, ITEM_UNIT, ITEM_COST, ITM_SAFE_STOCK, COMPANY_CODE;
	String ITM_FILE_NM, ITM_FILE_RENM, ITM_API_FNM;
	String ITM_USE_FLAG, ITM_EXP_FLAG, ITM_MEMO, ITM_INSERT_DATE, ITM_MODIFY_DATE;
	
	//거래처 컬럼
	String COMPANY_NAME, COM_USE_FLAG;

}
